# Generated by Django 4.0.2 on 2022-02-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_menumodel_price_alter_menumodel_price_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=200, null=True)),
                ('game_type', models.CharField(max_length=50, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
