# Generated by Django 4.0.2 on 2022-02-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_usermodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesmodel',
            name='image',
            field=models.ImageField(blank=True, default='avatar.svg', null=True, upload_to=''),
        ),
    ]
