# Generated by Django 4.0.2 on 2022-02-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_ordersmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmodel',
            name='expire_time',
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='duration_time',
            field=models.DurationField(null=True),
        ),
    ]
