# Generated by Django 4.0.2 on 2022-02-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_ordersmodel_expire_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmodel',
            name='duration_time',
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='expired_time',
            field=models.DateTimeField(null=True),
        ),
    ]
