# Generated by Django 4.0.2 on 2022-02-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_ordersmodel_expired_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodel',
            name='order_date',
            field=models.DateField(null=True),
        ),
    ]
