# Generated by Django 4.0.2 on 2022-02-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_ordersmodel_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmodel',
            name='order_time',
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='order_date',
            field=models.DateTimeField(null=True),
        ),
    ]
