# Generated by Django 4.0.2 on 2022-02-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_ordersmodel_order_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='expired_time',
            field=models.DateTimeField(null=True),
        ),
    ]
